version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test28Project
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri/Test28Project
  gitUsername: Munatri
  gitBranch: main
- name: CustomPackage
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
- name: TestRepo1
  gitServerName: PT
  gitUrl: https://github.com/Pratibha24
  gitUsername: Pratibha24
  gitBranch: main
